export function createMediaFeedRuntime() {
  return {
    decodedImageCache: new Map(),
    mediaDimensionCache: new Map(),
    audioWaveformCache: new Map(),
    audioWaveformJobs: new Map(),
    audioWaveformQueue: [],
    activeAudioWaveformLoads: 0,
    audioWaveformContext: null,
    floatingView: null,
    floatingWorkspaceResizeObserver: null,
    floatingWorkspaceMutationObserver: null,
    floatingWorkspaceElement: null,
    floatingCanvasControlsResizeObserver: null,
    floatingCanvasControlsElements: [],
    floatingTopProgressResizeObserver: null,
    floatingTopProgressElements: [],
    floatingBoundsAnimationFrame: 0,
    floatingBoundsWindowListenerAdded: false,
    setupComplete: false,
    placementSettingSeen: false,
    promptSettingSeen: false,
    showComfyProgressSettingSeen: false,
    scaleViewerMediaSettingSeen: false,
    viewerFitScaleSettingSeen: false,
    followLatestSettingSeen: false,
    metadataPositionSettingSeen: false,
    excludePreviewMediaSettingSeen: false,
    showFavoriteButtonSettingSeen: false,
    feedStyleSettingSeen: false,
    mediaScopeSettingSeen: false,
    batchDividersSettingSeen: false,
    loopVideosSettingSeen: false,
    loopAudioSettingSeen: false,
    viewer: null,
    viewerWheelLock: false,
    workflowTabSequence: 0,
    activeWorkflowTabId: "",
    activeQueueRequest: null,
    workflowTabIds: new WeakMap(),
    promptWorkflowTabs: new Map(),
    pendingQueueRequests: [],
    missingMediaChecks: new Set(),
    copyFeedbackTimers: new WeakMap(),
  };
}
